# config for streaming pipeline
# Anik Das - 2025EM1100026

postgres:
  jdbc_url: "jdbc:postgresql://postgres:5432/food_delivery_db"
  host: postgres
  port: 5432
  db: "food_delivery_db"
  user: "student"
  password: "student123"
  table: orders_2025EM1100026

kafka:
  brokers: "kafka:9092"
  topic: "2025EM1100026_food_orders_raw"

datalake:
  path: "/datalake/output/orders"
  format: "parquet"

streaming:
  checkpoint_location: "/datalake/checkpoints/orders"
  last_processed_timestamp_location: "/datalake/lastprocess/orders"
  batch_interval: 5